// reactjs/src/with-components/App.tsx
import * as React from 'react';
import ButtonCounter from './ButtonCounter';

export interface AppProps {}
 
export interface AppState {
  counter: number
}
 
class App extends React.Component<AppProps, AppState> {
  constructor(props: AppProps) {
    super(props);
    this.state = {
      counter: 0
    };
  }

  increment() {
    this.setState({ counter: this.state.counter + 1 });
  }
  
  decrement() {
    this.setState({ counter: this.state.counter - 1 });
  }

  render() { 
    return <>
      <span>{this.state.counter}</span>
      <div className="button-group">
          <ButtonCounter onClick={this.increment.bind(this)} label="Incrémenter"/>
          <ButtonCounter onClick={this.decrement.bind(this)} label="Décrémenter"/>
      </div>
    </>
  }
}
 
export default App;

// svelte/src/App.svelte
<script>
	import CounterButton from "./CounterButton.svelte";

	export let counter;

	export function increment() {
		counter++;
	}

	export function decrement() {
		counter--;
	}
</script>

<div id="app">
	<span>{counter}</span>
	<div class="button-group">
		<CounterButton action={increment} label="Incrémenter" />
		<CounterButton action={decrement} label="Décrémenter" />
	</div>
</div>
