// svelte/src/App.svelte
<script>
	import CounterButton from "./CounterButton.svelte";

	export let counter;

	export function increment() {
		counter++;
	}

	export function decrement() {
		counter--;
	}
</script>

<div id="app">
	<span>{counter}</span>
	<div class="button-group">
		<CounterButton action={increment} label="Incrémenter" />
		<CounterButton action={decrement} label="Décrémenter" />
	</div>
</div>

// reactjs/src/with-hooks/App.tsx
import React from "react";
import ButtonCounter from "./ButtonCounter";

export default function App() {
    const [counter, setCounter] = React.useState(0);
    
    return <>
        <span>{counter}</span>
        <div className="button-group">
            <ButtonCounter onClick={() => setCounter(counter + 1)} label="Incrémenter"/>
            <ButtonCounter onClick={() => setCounter(counter - 1)} label="Décrémenter"/>
        </div>
    </>
}
